### ISSUE TITLE
font-size mixin doesn't create the same values as YUI recommends

### ISSUE THREAD

**Issue by heygrady** [sporkd/compass-html5-boilerplate#2]
The table at YUI is recommending the percentage with a ceil() applied. I'm not positive if it makes a difference but the mixin that you have for this will generate different numbers.

12px / 13px = 0.9230769230769231 = 92.307...%
YUI says 93%

You have:
    @mixin font-size($size, $base-font-size: $base-font-size) {
      font-size: percentage($size / $base-font-size);
    }

It might be better to use:
    @mixin font-size($size, $base-font-size: $base-font-size) {
      font-size: ceil(percentage($size / $base-font-size));
    }

**Comment by sporkd** [comment]
Thanks Grady,

I implemented your suggestion for this latest release.  Curiously enough, the calculations still fall apart for sizes higher than 21px.  (Compare the values below to http://developer.yahoo.com/yui/3/cssfonts/#fontsize).  My guess is the yui team used arbitrary values based on actual displays since I cannot find any rhyme or reason for the differences.

```
font-size(10px) => font-size: 77%
font-size(11px) => font-size: 85%
font-size(12px) => font-size: 93%
font-size(13px) => font-size: 100%
font-size(14px) => font-size: 108%
font-size(15px) => font-size: 116%
font-size(16px) => font-size: 124%
font-size(17px) => font-size: 131%
font-size(18px) => font-size: 139%
font-size(19px) => font-size: 147%
font-size(20px) => font-size: 154%
font-size(21px) => font-size: 162%
font-size(22px) => font-size: 170%
font-size(23px) => font-size: 177%
font-size(24px) => font-size: 185%
font-size(25px) => font-size: 193%
font-size(26px) => font-size: 200%
```
