### ISSUE TITLE
change haml parsing options

### ISSUE THREAD

**Issue by rizkysyazuli** [sporkd/compass-html5-boilerplate#4]
how do i modify the haml template output from inside this extension? I'm aware that haml has options to modify the html output. like using double quotes instead of an apostrophe for attributes or preserving newlines, etc..

i can learn my way around the extension. but I'm not really familiar with haml, and ruby is definitely not in my territory :)

I'm forking this extension to update it with the latest boilerplate changes. but if you don't mind, i need the generated files to be as similar as possible with the original html5 boilerplate.

**Comment by sporkd** [comment]
After you run the compass command, it generates the haml files in your project.  You can then modify those haml files.  So for a rails project you will have:

app/views/layouts/application.html.haml
app/views/layouts/_flashes.html.haml
app/views/layouts/_footer.html.haml
app/views/layouts/_head.html.haml
app/views/layouts/_header.html.haml
app/views/layouts/_javascripts.html.haml
app/views/layouts/_stylesheets.html.haml

However, for a standalone project, the haml gets converted into an index.html.  So if you want to edit that haml, you would need to fork the project and modify  templates/index.html.haml.

The reason is that standalone projects don't really have haml support.  I suppose you could just copy the haml template as is, but then an additional step would be necessary to convert the haml to html.  Inside a rails project, this is done for you. Does this answer your question?

**Comment by sporkd** [comment]
The manifest file now copies the index.html.haml template into your stand-alone project in addition to the generated index.html file.  You will of course need to work out the compilation yourself.

**Comment by rizkysyazuli** [comment]
ah, that's better.. coz I'm considering using one of the php port of the ruby haml parser. I'm sure other (non-ruby) developers can take advantage of this.
