### ISSUE TITLE
include the new boilerplate build script

### ISSUE THREAD

**Issue by rizkysyazuli** [sporkd/compass-html5-boilerplate#5]
i want to include the latest build script from html5-boilerplate. should i list down _all_ the included files in the manifest? like this:

```
file 'files/build/build.xml', :to => 'build/build.xml'
file 'files/build/buildinfo.properties', :to => 'build/buildinfo.properties'
file 'files/build/createproject.sh', :to => 'build/createproject.sh'
file 'files/build/config/build.properties', :to => 'build/config/build.properties'
file 'files/build/config/default.properties', :to => 'build/config/default.properties'
file 'files/build/config/project.properties', :to => 'build/config/project.properties'
...
```

am i doing it right? this list will get very long.. is there a better way to do it?

**Comment by sporkd** [comment]
Well, you wouldn't want to include the build stuff for a rails project since rails and compass does much of the same stuff at runtime that the build does.  So I have not really kept up with the new build script functionality on html5-boilerplate.  If you wanted to use compass with html5 boilerplate in a non ruby web framework, I would probably recommend forking html5-boilerplate itself and adding compass and haml processing to their build process.

**Comment by sporkd** [comment]
Edited and closed.
